#!/usr/bin/env python
# -*- coding: utf-8 -*-



# This is the env and dqn parameters file.


# ENV CONFIG

SCREEN_WIDTH = 600
SCREEN_HIGHT = 1000
BOOST_H = 4
BOOST_V = 12
GRAVITY = 0.85
HIGHEST_Y_CHECK_EVERY = 400
HIGHEST_MIN_IMPROVEMENT = 100
BAR_HEIGHT = 30
TUNNEL_SPACE = 500
TUNNEL_OPENNESS = 230
BLOCK_SIZE = 30
PLAYER_SIZE = 26
NO_OP_MAX = 300
MAX_SCORE = 0
SHOW_PREVIEW = True
ACTION_SPACE_SIZE = 3


# dqn config

REPLAY_MEMORY_SIZE = 50000
MIN_REPLAY_MEMORY_SIZE = 1000
MODEL_NAME = "amamzingbrick"
MINIBATCH_SIZE = 128
DISCOUNT = 0.99
UPDATE_TARGET_EVERY = 5
OBSERVATION_SPACE_VALUES = (3, 3, 2)
LOAD_MODEL = None




